#!/usr/bin/env bash

kill_splash () {
  for i in {0..10}; do
    killall ksplashqml
    sleep 0.1
  done
}

kill_splash &
dunst &
picom &
xset r rate 200 70
onedrive -m &

# this is a simple config for herbstluftwm

hc() {
  herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000000'

# remove all existing keybindings
hc keyunbind --all

Mod=Mod1    # Use alt as the main modifier
hc set default_frame_layout vertical

hc keybind $Mod-Shift-i reload
hc keybind $Mod-Escape close_or_remove
hc keybind $Mod-Shift-c close_and_remove
hc keybind $Mod-Return spawn /home/mifrandir/.cargo/bin/alacritty

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-slash       split   right  0.5
hc keybind $Mod-minus       split   bottom   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tags=( q w e r  a s d f  )

hc rename default "${tags[0]}" || true
for i in "${!tags[@]}" ; do
  hc add "${tags[$i]}"
  key="${tags[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
# hc keybind $Mod-r remove
# hc keybind $Mod-s floating toggle
hc keybind $Mod-z fullscreen toggle
hc keybind $Mod-Shift-z set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
  or , and . compare tags.focus.curframe_wcount = 2                   \
  . cycle_layout +1 vertical horizontal max    \
  , cycle_layout +1

# mouse
hc mouseunbind --all

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-p spawn rofi -show run

# theme
hc attr theme.active.reset 1
hc attr theme.floating.reset 1
hc attr theme.reset 1
hc set frame_border_inner_width 5
hc set frame_border_normal_color '#2a2e32'
hc set frame_border_active_color '#6f7275'
hc set frame_border_width 4
hc set frame_bg_transparent on
hc set frame_gap 0
hc set always_show_frame off
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc attr theme.border_width 5
hc attr theme.outer_width 0
hc attr theme.outer_color '#000000'
hc attr theme.active.outer_width 4
hc attr theme.active.outer_color '#3ba1d6'


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class='plasmashell' floating=on
hc rule class='krunner' floating=on
hc rule class='pinentry-qt' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
